// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TakasakiStudio.Lina.Database.Context;

#nullable disable

namespace Hanabi.Core.Migrations
{
    [DbContext(typeof(LinaDbContext))]
    [Migration("20231108185428_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hanabi.Core.Models.ServerConfigurations", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("LogsChatId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("server_configurations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
