// <auto-generated />
using System;
using Lina.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hanabi.Core.Migrations
{
    [DbContext(typeof(LinaDbContext))]
    partial class LinaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hanabi.Core.Models.ServerConfigurations", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("LogsChatId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("server_configurations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
